/**
 * Shared "You Don't Know Jack" game-show look & feel for a VERTICAL 1080x1920
 * (9:16) social video: palette, fonts, sound cues, and reusable node/animation
 * helpers used across every scene.
 */
import {Gradient, Layout, Node, Rect, Txt} from '@canvas-commons/2d';
import {
  all,
  createRef,
  easeOutBack,
  easeOutCubic,
  Reference,
  sound,
  ThreadGenerator,
} from '@canvas-commons/core';

export const W = 1080;
export const H = 1920;

export const COLORS = {
  bg0: '#12052b',
  bg1: '#2a0f5c',
  ink: '#0b0118',
  white: '#fdfdff',
  yellow: '#ffd23f',
  cyan: '#22e0c8',
  magenta: '#ff2e88',
  blue: '#3a86ff',
  red: '#ff3b5c',
  green: '#4ade80',
  dim: '#b8a9d9',
};

// Heavy display face for the game-show shouting; clean face for body copy.
export const DISPLAY = '"Arial Black", Impact, "Haettenschweiler", sans-serif';
export const BODY = '"Trebuchet MS", "Segoe UI", Arial, sans-serif';

/**
 * Fire a sound cue at the current frame. Files live in `public/audio/`, so they
 * resolve at `/audio/<name>.wav` for both the editor preview and the FFmpeg
 * render. Generated by `tools/gen_sfx.py`.
 */
export function sfx(name: string, gainDb = 0): void {
  sound(`/audio/${name}.wav`).gain(gainDb).play();
}

/** Full-bleed gradient backdrop with faint floating "?" marks. */
export function makeBackground(accent: string = COLORS.magenta): Node {
  const marks: Node[] = [];
  const spots: [number, number, number, number][] = [
    [-360, -740, -18, 240],
    [330, -560, 14, 180],
    [-300, -180, 10, 160],
    [360, 160, -12, 260],
    [-330, 540, 22, 150],
    [300, 800, -8, 200],
  ];
  for (const [x, y, r, s] of spots) {
    marks.push(
      (
        <Txt
          text="?"
          fontFamily={DISPLAY}
          fontWeight={900}
          fontSize={s}
          fill={accent}
          opacity={0.06}
          x={x}
          y={y}
          rotation={r}
        />
      ) as Txt,
    );
  }
  return (
    <Rect
      width={W}
      height={H}
      fill={
        new Gradient({
          type: 'linear',
          from: [0, -H / 2],
          to: [0, H / 2],
          stops: [
            {offset: 0, color: COLORS.bg1},
            {offset: 1, color: COLORS.bg0},
          ],
        })
      }
    >
      {marks}
    </Rect>
  ) as Rect;
}

/** Bottom "host caption" bar — the snarky narrator's voice as on-screen text. */
export function HostBar(props: {
  barRef: Reference<Rect>;
  labelRef: Reference<Txt>;
}): Node {
  return (
    <Rect
      ref={props.barRef}
      y={H / 2 - 150}
      width={W - 80}
      height={210}
      radius={22}
      fill={COLORS.ink}
      stroke={COLORS.yellow}
      lineWidth={4}
      opacity={0}
      shadowColor={'#00000088'}
      shadowBlur={24}
      shadowOffset={[0, 10]}
      padding={28}
      alignItems={'center'}
      justifyContent={'center'}
    >
      <Txt
        ref={props.labelRef}
        text=""
        fontFamily={BODY}
        fontWeight={700}
        fontSize={46}
        fill={COLORS.white}
        width={W - 160}
        textAlign={'center'}
        textWrap
      />
    </Rect>
  ) as Rect;
}

/** Pop a node in with an overshoot — the signature game-show "slam". */
export function* popIn(node: Reference<Node>, time = 0.45): ThreadGenerator {
  yield* all(node().scale(1, time, easeOutBack), node().opacity(1, time * 0.7));
}

/** Set the host line, then fade the bar in (or swap text if already shown). */
export function* say(
  bar: Reference<Rect>,
  label: Reference<Txt>,
  text: string,
): ThreadGenerator {
  label().text(text);
  if (bar().opacity() < 1) {
    yield* bar().opacity(1, 0.3);
  }
}

/** A bold rounded "answer chip" for multiple-choice rows (vertical width). */
export function AnswerChip(props: {
  ref: Reference<Rect>;
  letter: string;
  text: string;
  y: number;
  accent?: string;
}): Node {
  const accent = props.accent ?? COLORS.blue;
  return (
    <Rect
      ref={props.ref}
      y={props.y}
      width={960}
      height={150}
      radius={18}
      fill={'#1c0c3d'}
      stroke={accent}
      lineWidth={4}
      opacity={0}
      scale={0.9}
      layout
      alignItems={'center'}
      padding={24}
      gap={28}
    >
      <Rect
        width={92}
        height={92}
        radius={14}
        fill={accent}
        alignItems={'center'}
        justifyContent={'center'}
      >
        <Txt
          text={props.letter}
          fontFamily={DISPLAY}
          fontWeight={900}
          fontSize={56}
          fill={COLORS.ink}
        />
      </Rect>
      <Txt
        text={props.text}
        fontFamily={BODY}
        fontWeight={700}
        fontSize={46}
        fill={COLORS.white}
        width={740}
        textWrap
      />
    </Rect>
  ) as Rect;
}

/** Flash a chip to the "correct" green and scale it up a touch. */
export function* markCorrect(chip: Reference<Rect>): ThreadGenerator {
  yield* all(
    chip().fill(COLORS.green, 0.3),
    chip().stroke(COLORS.white, 0.3),
    chip().scale(1.05, 0.3, easeOutCubic),
  );
}

export {Layout};
