/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/advocacy/email/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Advocacy Email
         * @description Generate advocacy email for an opportunity.
         */
        post: operations["generate_advocacy_email_api_advocacy_email__opportunity_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agents Status
         * @description Get status of all agents.
         */
        get: operations["get_agents_status_api_agents_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch-jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batch Jobs */
        get: operations["list_batch_jobs_api_batch_jobs__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch-jobs/failed-videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Failed Videos
         * @description Per-video failure log extracted from batch payloads (not summary counts only).
         */
        get: operations["list_failed_videos_api_batch_jobs_failed_videos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch-jobs/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Launch Status
         * @description Per-step running/stalled state for the dashboard's Run buttons.
         */
        get: operations["launch_status_api_batch_jobs_launch_get"];
        put?: never;
        /**
         * Launch Pipeline
         * @description (Re)launch a pipeline step. Refuses if a run is already active.
         */
        post: operations["launch_pipeline_api_batch_jobs_launch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch-jobs/launch/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Launch Log */
        get: operations["launch_log_api_batch_jobs_launch_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch-jobs/launch/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Pipeline
         * @description Stop running pipeline launch(es). Signals the detached process group so the
         *     whole subtree exits. ``step`` targets one step; omit it to stop everything.
         */
        post: operations["stop_pipeline_api_batch_jobs_launch_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch-jobs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Batch Jobs
         * @description SSE stream of dashboard JSON; pushes when DB revision changes.
         */
        get: operations["stream_batch_jobs_api_batch_jobs_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch-jobs/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch Job */
        get: operations["get_batch_job_api_batch_jobs__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch-jobs/{batch_id}/jurisdictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Batch Jurisdictions
         * @description Slim jurisdiction rows for one state (loaded on demand; no per-video arrays).
         */
        get: operations["list_batch_jurisdictions_api_batch_jobs__batch_id__jurisdictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Stats
         * @description Get dashboard statistics and recent opportunities.
         */
        get: operations["get_dashboard_stats_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/ingest/census": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Census Data
         * @description Trigger Census Bureau jurisdiction data ingestion.
         *
         *     Downloads and processes:
         *     - 3,144 counties
         *     - 19,500+ municipalities
         *     - 36,000+ townships
         *     - 13,000+ school districts
         *
         *     This is a long-running operation that runs in the background.
         */
        post: operations["ingest_census_data_api_data_ingest_census_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/ingest/nces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Nces Data
         * @description Trigger NCES school district data ingestion.
         *
         *     Downloads and processes 13,000+ school districts with:
         *     - District names and addresses
         *     - Contact information
         *     - NCES IDs
         *     - Enrollment data
         */
        post: operations["ingest_nces_data_api_data_ingest_nces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/ingest/nonprofits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Nonprofits
         * @description Trigger nonprofit data ingestion for a specific state.
         *
         *     Bulk downloads nonprofit data from ProPublica API and caches locally.
         *
         *     Example: POST /api/data/ingest/nonprofits?state=AL&ntee_codes=E&ntee_codes=E20
         */
        post: operations["ingest_nonprofits_api_data_ingest_nonprofits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data Status
         * @description Get status of all reference data ingestions.
         *
         *     Returns counts and last update times for:
         *     - Census jurisdictions
         *     - NCES school districts
         *     - Nonprofit organizations
         *     - Meeting datasets (MeetingBank, LocalView, etc.)
         */
        get: operations["get_data_status_api_data_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deployments */
        get: operations["list_deployments_api_deployments__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployments/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Deployment */
        post: operations["launch_deployment_api_deployments_launch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployments/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deployment */
        get: operations["get_deployment_api_deployments__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployments/{job_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deployment Log */
        get: operations["deployment_log_api_deployments__job_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployments/{job_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Deployment */
        post: operations["stop_deployment_api_deployments__job_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Documents
         * @description Get analyzed documents with pagination.
         */
        get: operations["get_documents_api_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jurisdictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Jurisdictions
         * @description Query ingested Census jurisdiction data.
         *
         *     Returns government entities with FIPS codes, coordinates, and population.
         */
        get: operations["get_jurisdictions_api_jurisdictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nonprofits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Nonprofits
         * @description Search for nonprofits using free open data APIs.
         *
         *     Integrates data from:
         *     - ProPublica Nonprofit Explorer (financial data, NTEE codes)
         *     - Every.org (mission statements, logos)
         *     - IRS TEOS (official tax-exempt status)
         *
         *     Example: /api/nonprofits?location=Tuscaloosa,AL&keyword=dental&ntee_code=E
         */
        get: operations["search_nonprofits_api_nonprofits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nonprofits/compensation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nonprofit Compensation
         * @description Person-level executive/board compensation from the GivingTuesday 990 datamarts
         *     (Form 990 Part VII-A + Schedule J detail), joined to organization context.
         *
         *     Examples:
         *       /api/nonprofits/compensation?ein=530196605            (one org's people)
         *       /api/nonprofits/compensation?state=NY&min_comp=500000 (top earners in NY)
         *       /api/nonprofits/compensation?person=smith&sort=comp-desc
         */
        get: operations["nonprofit_compensation_api_nonprofits_compensation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Opportunities
         * @description Get advocacy opportunities with optional filters.
         */
        get: operations["get_opportunities_api_opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/school-districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get School Districts
         * @description Query ingested NCES school district data.
         *
         *     Returns school districts with contact information and enrollment.
         */
        get: operations["get_school_districts_api_school_districts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search All
         * @description Unified search across contacts, organizations, causes, and jurisdictions.
         *     Returns results grouped by type with pagination.
         */
        get: operations["search_all_api_search__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Get current system settings.
         */
        get: operations["get_settings_api_settings_get"];
        /**
         * Update Settings
         * @description Update system settings.
         */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Workflow
         * @description Start a new analysis workflow.
         */
        post: operations["start_workflow_api_workflow_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/{workflow_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workflow Status
         * @description Get status of a running workflow.
         */
        get: operations["get_workflow_status_api_workflow__workflow_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve React App
         * @description Serve a real static file if one exists, else the React app (SPA routing).
         *
         *     Top-level public assets (e.g. /pdf/*, /communityone_logo.svg,
         *     /robots.txt, /wikimedia/*) live in static_dir but are not under the
         *     mounted /assets or /data trees. Without this file check they fall through
         *     to index.html, so the browser loads the SPA into e.g. an <iframe
         *     src="/pdf/..."> and React Router renders the NotFound (404) page instead
         *     of the file. Vite's dev server serves these from public/ at the root, so
         *     the gap only shows in production.
         */
        get: operations["serve_react_app__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchJobModel */
        BatchJobModel: {
            /** Batch Id */
            batch_id: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Finished At
             * @default
             */
            finished_at: string;
            /** Jurisdictions */
            jurisdictions?: components["schemas"]["JurisdictionRunModel"][];
            /**
             * Started At
             * @default
             */
            started_at: string;
            /** Status */
            status: string;
            /** Step */
            step: string;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * @default
             */
            updated_at: string;
        };
        /** BatchJobsDashboardResponse */
        BatchJobsDashboardResponse: {
            /** Batches */
            batches: components["schemas"]["BatchJobModel"][];
            /**
             * Detail
             * @default full
             */
            detail: string;
            /** Generated At */
            generated_at: string;
            /**
             * Last Activity At
             * @default
             */
            last_activity_at: string;
            /**
             * Source
             * @default database
             */
            source: string;
            stage_report?: components["schemas"]["StageReport"];
            totals: components["schemas"]["BatchJobsTotals"];
        };
        /** BatchJobsTotals */
        BatchJobsTotals: {
            /**
             * Batches
             * @default 0
             */
            batches: number;
            /**
             * Bronze Download Rows
             * @default 0
             */
            bronze_download_rows: number;
            /**
             * Failed Jurisdictions
             * @default 0
             */
            failed_jurisdictions: number;
            /**
             * Files Analysis
             * @default 0
             */
            files_analysis: number;
            /**
             * Files Analysis Errors Recent
             * @default 0
             */
            files_analysis_errors_recent: number;
            /**
             * Files Analysis Recent
             * @default 0
             */
            files_analysis_recent: number;
            /**
             * Files Reports
             * @default 0
             */
            files_reports: number;
            /**
             * Files Reports Errors Recent
             * @default 0
             */
            files_reports_errors_recent: number;
            /**
             * Files Reports Recent
             * @default 0
             */
            files_reports_recent: number;
            /**
             * Files Transcripts
             * @default 0
             */
            files_transcripts: number;
            /**
             * Files Transcripts Disk
             * @default 0
             */
            files_transcripts_disk: number;
            /**
             * Last Analysis At
             * @default
             */
            last_analysis_at: string;
            /**
             * Last Report At
             * @default
             */
            last_report_at: string;
            /**
             * Last Transcript At
             * @default
             */
            last_transcript_at: string;
            /**
             * Processed Jurisdictions
             * @default 0
             */
            processed_jurisdictions: number;
            /**
             * Remaining Jurisdictions
             * @default 0
             */
            remaining_jurisdictions: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * States
             * @default 0
             */
            states: number;
            /**
             * States Completed
             * @default 0
             */
            states_completed: number;
            /**
             * States Planned
             * @default 0
             */
            states_planned: number;
            /**
             * States Started
             * @default 0
             */
            states_started: number;
            /**
             * Transcript Hours
             * @default 0
             */
            transcript_hours: number;
            /**
             * Videos Attempted
             * @default 0
             */
            videos_attempted: number;
            /**
             * Videos Fail
             * @default 0
             */
            videos_fail: number;
            /**
             * Videos Ok
             * @default 0
             */
            videos_ok: number;
        };
        /** BatchJurisdictionsResponse */
        BatchJurisdictionsResponse: {
            /** Batch Id */
            batch_id: string;
            /** Jurisdictions */
            jurisdictions?: components["schemas"]["JurisdictionRunModel"][];
            /** State Code */
            state_code: string;
        };
        /** DeploymentJobModel */
        DeploymentJobModel: {
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /** Finished At */
            finished_at?: string | null;
            /** Job Id */
            job_id: string;
            /**
             * Job Type
             * @default deployment
             */
            job_type: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Live
             * @default false
             */
            live: boolean;
            /** Pid */
            pid?: number | null;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @default running
             */
            status: string;
            /** Steps */
            steps?: components["schemas"]["DeploymentStepModel"][];
            /** Updated At */
            updated_at?: string | null;
        };
        /** DeploymentLogResponse */
        DeploymentLogResponse: {
            /** Job Id */
            job_id: string;
            /** Lines */
            lines?: string[];
            /**
             * Path
             * @default
             */
            path: string;
            /** Step */
            step: string;
        };
        /** DeploymentStepModel */
        DeploymentStepModel: {
            /**
             * Cmd
             * @default
             */
            cmd: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Exit Code */
            exit_code?: number | null;
            /** Finished At */
            finished_at?: string | null;
            /** Key */
            key: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Log
             * @default
             */
            log: string;
            /** Note */
            note?: string | null;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @default pending
             */
            status: string;
            /**
             * Target
             * @default
             */
            target: string;
        };
        /** DeploymentsListResponse */
        DeploymentsListResponse: {
            /** Available Steps */
            available_steps?: components["schemas"]["StepDefModel"][];
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Jobs */
            jobs?: components["schemas"]["DeploymentJobModel"][];
        };
        /** FailedVideoRowModel */
        FailedVideoRowModel: {
            /** Batch Id */
            batch_id: string;
            /**
             * Batch Step
             * @default
             */
            batch_step: string;
            /**
             * Jurisdiction Id
             * @default
             */
            jurisdiction_id: string;
            /**
             * Jurisdiction Name
             * @default
             */
            jurisdiction_name: string;
            /**
             * State Code
             * @default
             */
            state_code: string;
            video: components["schemas"]["VideoResultModel"];
        };
        /** FailedVideosListResponse */
        FailedVideosListResponse: {
            /** Rows */
            rows?: components["schemas"]["FailedVideoRowModel"][];
            /**
             * Total Fail In Summaries
             * @default 0
             */
            total_fail_in_summaries: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JurisdictionRunModel */
        JurisdictionRunModel: {
            /**
             * Current Video Id
             * @default
             */
            current_video_id: string;
            /**
             * Current Video Started At
             * @default
             */
            current_video_started_at: string;
            /**
             * Current Video Title
             * @default
             */
            current_video_title: string;
            /**
             * Elapsed Seconds
             * @default 0
             */
            elapsed_seconds: number;
            /**
             * Exit Code
             * @default 0
             */
            exit_code: number;
            /** File Counts */
            file_counts?: {
                [key: string]: number;
            };
            /**
             * Finished At
             * @default
             */
            finished_at: string;
            /** Jurisdiction Id */
            jurisdiction_id: string;
            /**
             * Jurisdiction Name
             * @default
             */
            jurisdiction_name: string;
            /**
             * Started At
             * @default
             */
            started_at: string;
            /** State Code */
            state_code: string;
            /** Stats */
            stats?: {
                [key: string]: number;
            };
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Videos */
            videos?: components["schemas"]["VideoResultModel"][];
        };
        /** LaunchDeploymentRequest */
        LaunchDeploymentRequest: {
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            /** Steps */
            steps?: string[];
        };
        /** LaunchDeploymentResponse */
        LaunchDeploymentResponse: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            /**
             * Job Id
             * @default
             */
            job_id: string;
            /** Launched */
            launched: boolean;
            /** Pid */
            pid?: number | null;
            /** Steps */
            steps?: string[];
        };
        /** LaunchLogResponse */
        LaunchLogResponse: {
            /**
             * Current
             * @default
             */
            current: string;
            /**
             * Current Since
             * @default
             */
            current_since: string;
            /** Lines */
            lines?: string[];
            /**
             * Path
             * @default
             */
            path: string;
            /** Step */
            step: string;
        };
        /** LaunchRequest */
        LaunchRequest: {
            /**
             * N
             * @default 10
             */
            n: number;
            /**
             * Parallel
             * @default 4
             */
            parallel: number;
            /** States */
            states?: string[];
            /**
             * Step
             * @default analyze
             */
            step: string;
        };
        /** LaunchResponse */
        LaunchResponse: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Launched */
            launched: boolean;
            /**
             * Log
             * @default
             */
            log: string;
            /** Pid */
            pid?: number | null;
            /** States */
            states?: string[];
            /**
             * Step
             * @default
             */
            step: string;
        };
        /** LaunchStatusResponse */
        LaunchStatusResponse: {
            /**
             * Busy
             * @default false
             */
            busy: boolean;
            /** Enabled */
            enabled: boolean;
            /**
             * Running
             * @default 0
             */
            running: number;
            /** Running Steps */
            running_steps?: string[];
            /** Stalled Steps */
            stalled_steps?: string[];
            /** Steps */
            steps?: string[];
        };
        /** StageBreakdownEntry */
        StageBreakdownEntry: {
            /**
             * Done
             * @default 0
             */
            done: number;
            /** Entity */
            entity: string;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** StageReport */
        StageReport: {
            /** Rows */
            rows?: components["schemas"]["StageReportRow"][];
            /** States */
            states?: string[];
            /** Timing */
            timing?: {
                [key: string]: unknown;
            };
        };
        /** StageReportRow */
        StageReportRow: {
            /** Breakdown */
            breakdown?: components["schemas"]["StageBreakdownEntry"][];
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Last At
             * @default
             */
            last_at: string;
            /** Scope */
            scope: string;
            /** Stage */
            stage: string;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** StepDefModel */
        StepDefModel: {
            /** Description */
            description: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Target */
            target: string;
        };
        /** StopDeploymentResponse */
        StopDeploymentResponse: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Stopped
             * @default false
             */
            stopped: boolean;
        };
        /** StopRequest */
        StopRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Step */
            step?: string | null;
        };
        /** StopResponse */
        StopResponse: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Pids */
            pids?: number[];
            /** Steps */
            steps?: string[];
            /**
             * Stopped
             * @default 0
             */
            stopped: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoResultModel */
        VideoResultModel: {
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Error
             * @default
             */
            error: string;
            /**
             * Finished At
             * @default
             */
            finished_at: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Transcript Source
             * @default
             */
            transcript_source: string;
            /** Video Id */
            video_id: string;
        };
        /**
         * WorkflowRequest
         * @description Request to start a new analysis workflow.
         */
        WorkflowRequest: {
            /** Targets */
            targets: {
                [key: string]: string;
            }[];
            /** Topics */
            topics?: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_advocacy_email_api_advocacy_email__opportunity_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agents_status_api_agents_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_batch_jobs_api_batch_jobs__get: {
        parameters: {
            query?: {
                /** @description Scan policy cache on disk for analysis/report counts (slow) */
                refresh_files?: boolean;
                /** @description Refresh transcript metrics from bronze (slow; stream uses lighter enrich) */
                enrich_bronze?: boolean;
                /** @description summary = aggregates + batch list (default); standard/full load jurisdiction payloads (slow) */
                detail?: string;
                batch_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchJobsDashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_failed_videos_api_batch_jobs_failed_videos_get: {
        parameters: {
            query?: {
                /** @description Limit to one batch; omit for recent batches combined */
                batch_id?: string | null;
                limit?: number;
                batch_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailedVideosListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_status_api_batch_jobs_launch_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaunchStatusResponse"];
                };
            };
        };
    };
    launch_pipeline_api_batch_jobs_launch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaunchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_log_api_batch_jobs_launch_log_get: {
        parameters: {
            query: {
                /** @description Pipeline step whose latest log to tail */
                step: string;
                lines?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaunchLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_pipeline_api_batch_jobs_launch_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_batch_jobs_api_batch_jobs_stream_get: {
        parameters: {
            query?: {
                refresh_files?: boolean;
                /** @description When true, refresh transcript counts from bronze each tick (heavier) */
                enrich_bronze?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_job_api_batch_jobs__batch_id__get: {
        parameters: {
            query?: {
                refresh_files?: boolean;
                enrich_bronze?: boolean;
                /** @description all | failed_only | none — per-video rows for drill-down */
                include_videos?: string;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchJobModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batch_jurisdictions_api_batch_jobs__batch_id__jurisdictions_get: {
        parameters: {
            query: {
                /** @description USPS state code */
                state: string;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchJurisdictionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_stats_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ingest_census_data_api_data_ingest_census_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ingest_nces_data_api_data_ingest_nces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ingest_nonprofits_api_data_ingest_nonprofits_post: {
        parameters: {
            query: {
                /** @description 2-letter state code */
                state: string;
                /** @description NTEE codes to ingest */
                ntee_codes?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_status_api_data_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_deployments_api_deployments__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_deployment_api_deployments_launch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchDeploymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaunchDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deployment_api_deployments__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentJobModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deployment_log_api_deployments__job_id__log_get: {
        parameters: {
            query: {
                /** @description Step key whose log to tail. */
                step: string;
                lines?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_deployment_api_deployments__job_id__stop_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_documents_api_documents_get: {
        parameters: {
            query?: {
                search?: string | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_jurisdictions_api_jurisdictions_get: {
        parameters: {
            query?: {
                /** @description 2-letter state code */
                state?: string | null;
                /** @description Type: county, municipality, township */
                type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_nonprofits_api_nonprofits_get: {
        parameters: {
            query?: {
                /** @description City, State format */
                location?: string;
                /** @description Service keyword (e.g., 'dental', 'health') */
                keyword?: string | null;
                /** @description 2-letter state code (e.g., 'AL') */
                state?: string | null;
                /** @description NTEE code (e.g., 'E' for health) */
                ntee_code?: string | null;
                /** @description Data source: 'propublica', 'everyorg', 'all' */
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nonprofit_compensation_api_nonprofits_compensation_get: {
        parameters: {
            query?: {
                /** @description Exact EIN — a single org's people */
                ein?: string | null;
                /** @description 2-letter state code or full name */
                state?: string | null;
                /** @description Case-insensitive person-name search */
                person?: string | null;
                /** @description Minimum reportable comp from the org */
                min_comp?: number | null;
                limit?: number;
                offset?: number;
                /** @description comp-desc | comp-asc | name-asc */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunities_api_opportunities_get: {
        parameters: {
            query?: {
                state?: string | null;
                topic?: string | null;
                urgency?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_school_districts_api_school_districts_get: {
        parameters: {
            query?: {
                /** @description 2-letter state code */
                state?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_all_api_search__get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                /** @description Comma-separated types to search */
                types?: string | null;
                /** @description Filter by state code (e.g. MA, AL) */
                state?: string | null;
                limit?: number;
                page?: number;
                /** @description NTEE category code */
                ntee_code?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_workflow_api_workflow_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_status_api_workflow__workflow_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_react_app__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
