import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Shared "Data and Terms" sidebar. Surfaces the data catalog overview and the
// full Data Sources reference (formerly the standalone "Catalog" tab) alongside
// the citations and legal/terms docs.
const dataAndTermsSidebar = [
  {
    type: 'category' as const,
    label: 'Data and Terms',
    collapsed: false,
    items: [
      {
        type: 'doc' as const,
        id: 'data-sources/overview',
        label: 'Data Catalog',
      },
      {
        type: 'category' as const,
        label: 'Data Sources',
        items: [{type: 'autogenerated' as const, dirName: 'data-sources'}],
      },
      {
        type: 'doc' as const,
        id: 'legal/index',
        label: 'Terms and Privacy',
      },
    ],
  },
];

const sidebars: SidebarsConfig = {
  // ========================================
  // DIATAXIS DUAL SIDEBARS
  // ----------------------------------------
  // Two information-architecture views over the existing docs (no file moves):
  // a Developer Handbook for contributors (setup / build / extend) and a
  // Public Data Catalog for civic users (what's in the data, how to use it).
  // Each is grouped into the four Diataxis quadrants:
  //   Tutorials   - learning-oriented
  //   How-To      - task-oriented
  //   Reference   - information-oriented
  //   Explanation - understanding-oriented
  // Existing audience sidebars (gettingStarted / families / policyMakers /
  // developers / docs) are kept intact for now; retire them in a follow-up
  // once the dual-sidebar nav settles.
  // ========================================
  handbookSidebar: [
    {type: 'doc', id: 'for-developers', label: 'Developer Handbook'},
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        'quickstart',
        'quick-reference',
      ],
    },
    {
      type: 'category',
      label: 'How-To Guides',
      items: [
        'development/adding-data-sources',
        'guides/jurisdiction-setup',
        'guides/scraper-improvements',
        'guides/local-llm-web-scraping',
        'guides/huggingface-quickstart',
        'guides/huggingface-publishing',
        'guides/huggingface-features',
        'guides/huggingface-limits',
        'guides/legislative-tracking-maps',
        'guides/handling-formats',
        'guides/document-libraries',
        'guides/search-patterns',
        'guides/accessibility-testing',
        'guides/split-screen',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'architecture',
        {
          type: 'category',
          label: 'dbt (Data Build Tool)',
          items: [{type: 'autogenerated', dirName: 'dbt'}],
        },
        {
          type: 'category',
          label: 'Integrations',
          items: [{type: 'autogenerated', dirName: 'integrations'}],
        },
        {
          type: 'category',
          label: 'Deployment',
          items: [{type: 'autogenerated', dirName: 'deployment'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Explanation',
      items: [
        'development/dbt-etl-strategy',
        'development/database-driven-homepage',
        'development/dashboard-redesign',
        'development/state-field-naming-standard',
        'development/migration-v2',
      ],
    },
  ],

  // ========================================
  // GETTING STARTED - For Everyone
  // ========================================
  gettingStartedSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'intro',
        'open-navigator',
      ],
    },
    {
      type: 'doc',
      id: 'data-sources/citations',
      label: 'Citations & Data Sources',
    },
    {
      type: 'doc',
      id: 'legal-compliance',
      label: 'Legal & Compliance',
    },
  ],

  // ========================================
  // CITIZENS & RESIDENTS - Community Resources
  // ========================================
  familiesSidebar: [
    {
      type: 'category',
      label: 'Citizens and Residents',
      collapsed: false,
      items: [
        'for-families',
        {
          type: 'category',
          label: 'Resources for Citizens & Residents',
          items: [
            'families/community-events',
            'families/training-education',
            'families/voter-registration',
            'families/service-requests',
            'families/community-resources',
            'resources/nonprofit-resources',
          ],
        },
        {
          type: 'doc',
          id: 'open-navigator',
          label: 'Getting Started with Open Navigator',
        },
        {
          type: 'doc',
          id: 'data-sources/citations',
          label: 'Citations & Data Sources',
        },
        {
          type: 'doc',
          id: 'legal-compliance',
          label: 'Legal & Compliance',
        },
      ],
    },
  ],

  // ========================================
  // POLICY MAKERS - Non-Technical
  // ========================================
  policyMakersSidebar: [
    {
      type: 'category',
      label: 'Policy Makers & Advocates',
      collapsed: false,
      items: [
        'for-advocates',
        {
          type: 'category',
          label: '1. Define your cause / mission',
          items: ['resources/nonprofit-resources'],
        },
        {
          type: 'category',
          label: '2. Identify who to engage',
          items: [
            'data-sources/overview',
            {
              type: 'doc',
              id: 'data-sources/citations',
              label: 'Citations & Data Sources',
            },
            'data-sources/nonprofit-sources',
            'data-sources/video-sources',
          ],
        },
        {
          type: 'category',
          label: '3. Choose a strategy',
          items: [
            'guides/political-economy',
            'guides/accountability-strategy',
            'guides/impact-navigation',
          ],
        },
        {
          type: 'category',
          label: '4. Define what success looks like',
          items: [
            {
              type: 'autogenerated',
              dirName: 'case-studies',
            },
          ],
        },
      ],
    },
  ],

  // ========================================
  // DEVELOPERS - Technical
  // ========================================
  developersSidebar: [
    {
      type: 'category',
      label: 'Developers & Technical Users',
      collapsed: false,
      items: [
        'for-developers',
        {
          type: 'category',
          label: 'Hackathon',
          items: [
            'guides/hackathon-video-submission-ideas',
            'guides/hackathon/big-timber-tuscaloosa-jurisdiction-ids',
          ],
        },
        {
          type: 'category',
          label: 'Setup & Installation',
          items: [
            'quickstart',
            'quick-reference',
            'architecture',
          ],
        },
        {
          type: 'category',
          label: 'Data Sources (Technical)',
          items: [
            {
              type: 'doc',
              id: 'data-sources/citations',
              label: 'Citations & Data Sources',
            },
            {
              type: 'doc',
              id: 'legal-compliance',
              label: 'Legal & Compliance',
            },
            'data-sources/data-model-erd',
            'data-sources/jurisdiction-discovery',
            'data-sources/census-data',
            // 'data-sources/civic-tech-sources', // Temporarily disabled - MDX parsing issue
            'data-sources/huggingface-datasets',
            'data-sources/url-datasets',
            'data-sources/youtube-discovery',
            'data-sources/video-channels',
            'data-sources/open-source-repositories',
            'data-sources/ballot-election-sources',
            'data-sources/polling-survey-sources',
            'data-sources/factcheck-sources',
          ],
        },
        {
          type: 'category',
          label: 'How-To Guides',
          items: [
            'guides/accessibility-testing',
            'guides/jurisdiction-setup',
            'guides/legislative-tracking-maps',
            'guides/huggingface-publishing',
            'guides/huggingface-quickstart',
            'guides/huggingface-features',
            'guides/huggingface-limits',
            'guides/handling-formats',
            'guides/document-libraries',
            'guides/scraper-improvements',
            'guides/local-llm-web-scraping',
            'guides/search-patterns',
            'guides/split-screen',
          ],
        },
        {
          type: 'category',
          label: 'Integrations',
          items: [
            {
              type: 'autogenerated',
              dirName: 'integrations',
            },
          ],
        },
        {
          type: 'category',
          label: 'Deployment',
          items: [
            {
              type: 'autogenerated',
              dirName: 'deployment',
            },
          ],
        },
        {
          type: 'category',
          label: 'Development',
          items: [
            {
              type: 'autogenerated',
              dirName: 'development',
            },
          ],
        },
        {
          type: 'category',
          label: 'dbt (Data Build Tool)',
          items: [
            {
              type: 'autogenerated',
              dirName: 'dbt',
            },
          ],
        },
      ],
    },
  ],

  // ========================================
  // MAIN SIDEBAR - All Documentation
  // ========================================
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'intro',
        'open-navigator',
      ],
    },
    {
      type: 'category',
      label: 'Citizens and Residents',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'for-families',
      },
      items: [
        {
          type: 'category',
          label: 'Resources for Citizens & Residents',
          items: [
            'families/community-events',
            'families/training-education',
            'families/voter-registration',
            'families/service-requests',
            'families/community-resources',
          ],
        },
        {
          type: 'doc',
          id: 'open-navigator',
          label: 'Getting Started with Open Navigator',
        },
        {
          type: 'doc',
          id: 'data-sources/citations',
          label: 'Citations & Data Sources',
        },
      ],
    },
    {
      type: 'category',
      label: 'Policy Makers & Advocates',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'for-advocates',
      },
      items: [
        'for-advocates',
        {
          type: 'category',
          label: '1. Define your cause / mission',
          items: ['resources/nonprofit-resources'],
        },
        {
          type: 'category',
          label: '2. Identify who to engage',
          items: [
            'data-sources/overview',
            {
              type: 'doc',
              id: 'data-sources/citations',
              label: 'Citations & Data Sources',
            },
            'data-sources/nonprofit-sources',
            'data-sources/video-sources',
          ],
        },
        {
          type: 'category',
          label: '3. Choose a strategy',
          items: [
            'guides/political-economy',
            'guides/accountability-strategy',
            'guides/impact-navigation',
          ],
        },
        {
          type: 'category',
          label: '4. Define what success looks like',
          items: [
            {
              type: 'autogenerated',
              dirName: 'case-studies',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developers & Technical Users',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'for-developers',
      },
      items: [
        'for-developers',
        {
          type: 'category',
          label: 'Hackathon',
          items: [
            'guides/hackathon-video-submission-ideas',
            'guides/hackathon/big-timber-tuscaloosa-jurisdiction-ids',
          ],
        },
        {
          type: 'category',
          label: 'Setup & Installation',
          items: [
            'quickstart',
            'quick-reference',
            'architecture',
          ],
        },
        {
          type: 'category',
          label: 'Data Sources (Technical)',
          items: [
            {
              type: 'doc',
              id: 'data-sources/citations',
              label: 'Citations & Data Sources',
            },
            {
              type: 'doc',
              id: 'legal-compliance',
              label: 'Legal & Compliance',
            },
            'data-sources/data-model-erd',
            'data-sources/jurisdiction-discovery',
            'data-sources/census-data',
            'data-sources/huggingface-datasets',
            'data-sources/url-datasets',
            'data-sources/youtube-discovery',
            'data-sources/video-channels',
            'data-sources/open-source-repositories',
            'data-sources/ballot-election-sources',
            'data-sources/polling-survey-sources',
            'data-sources/factcheck-sources',
          ],
        },
        {
          type: 'category',
          label: 'How-To Guides',
          items: [
            'guides/accessibility-testing',
            'guides/jurisdiction-setup',
            'guides/legislative-tracking-maps',
            'guides/huggingface-publishing',
            'guides/huggingface-quickstart',
            'guides/huggingface-features',
            'guides/huggingface-limits',
            'guides/handling-formats',
            'guides/document-libraries',
            'guides/scraper-improvements',
            'guides/local-llm-web-scraping',
            'guides/search-patterns',
            'guides/split-screen',
          ],
        },
        {
          type: 'category',
          label: 'Integrations',
          items: [
            {
              type: 'autogenerated',
              dirName: 'integrations',
            },
          ],
        },
        {
          type: 'category',
          label: 'Deployment',
          items: [
            {
              type: 'autogenerated',
              dirName: 'deployment',
            },
          ],
        },
        {
          type: 'category',
          label: 'Development',
          items: [
            {
              type: 'autogenerated',
              dirName: 'development',
            },
          ],
        },
        {
          type: 'category',
          label: 'dbt (Data Build Tool)',
          items: [
            {
              type: 'autogenerated',
              dirName: 'dbt',
            },
          ],
        },
      ],
    },
  ],

  // ========================================
  // DATA AND TERMS - Standalone Sidebar
  // (Absorbs the former "Catalog" data content: the data catalog
  //  overview and the full Data Sources reference.)
  // ========================================
  citationsSidebar: dataAndTermsSidebar,

  // ========================================
  // LEGAL - Uses same sidebar as Data and Terms
  // ========================================
  legalSidebar: dataAndTermsSidebar,
};

export default sidebars;
